services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: article_like
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
